repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: name-tests-test
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-broken-line>=0.4.0,
            flake8-bugbear>=21.9.2,
            flake8-comprehensions>=3.7.0,
            flake8-debugger>=4.0.0,
            flake8-print>=4.0.0,
            flake8-quotes>=3.3.1,
            flake8-string-format>=0.3.0,
            flake8-typing-imports>=1.11.0,
            flake8-functions>=0.0.6,
            flake8-variables-names>=0.0.4,
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
